//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.16 at 01:40:51 PM EDT 
//


package org.cisecurity.oval.collection.ind;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;

import org.cisecurity.oval.collection.FilterType;
import org.cisecurity.oval.collection.ObjectIntType;
import org.cisecurity.oval.collection.ObjectStringType;
import org.cisecurity.oval.collection.ObjectType;
import org.cisecurity.oval.collection.Set;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://oval.cisecurity.org/XMLSchema/oval-collections-6}ObjectType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element ref="{http://oval.cisecurity.org/XMLSchema/oval-collections-6}set"/>
 *           &lt;sequence>
 *             &lt;element name="pid" type="{http://oval.cisecurity.org/XMLSchema/oval-collections-6}ObjectIntType"/>
 *             &lt;element name="name" type="{http://oval.cisecurity.org/XMLSchema/oval-collections-6}ObjectStringType"/>
 *             &lt;element ref="{http://oval.cisecurity.org/XMLSchema/oval-collections-6}filter" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name = "processenvironment_object")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "set",
    "pid",
    "name",
    "filter"
})
public class ProcessenvironmentObject
    extends ObjectType
{

    @XmlElement(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6")
    protected Set set;
    @XmlElementRef(name = "pid", namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#independent", type = JAXBElement.class, required = false)
    protected JAXBElement<ObjectIntType> pid;
    protected ObjectStringType name;
    @XmlElementRef(name = "filter", namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", type = JAXBElement.class, required = false)
    protected List<JAXBElement<? extends FilterType>> filter;

    /**
     * Gets the value of the set property.
     * 
     * @return
     *     possible object is
     *     {@link Set }
     *     
     */
    public Set getSet() {
        return set;
    }

    /**
     * Sets the value of the set property.
     * 
     * @param value
     *     allowed object is
     *     {@link Set }
     *     
     */
    public void setSet(Set value) {
        this.set = value;
    }

    /**
     * Gets the value of the pid property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ObjectIntType }{@code >}
     *     
     */
    public JAXBElement<ObjectIntType> getPid() {
        return pid;
    }

    /**
     * Sets the value of the pid property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ObjectIntType }{@code >}
     *     
     */
    public void setPid(JAXBElement<ObjectIntType> value) {
        this.pid = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectStringType }
     *     
     */
    public ObjectStringType getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectStringType }
     *     
     */
    public void setName(ObjectStringType value) {
        this.name = value;
    }

    /**
     * Gets the value of the filter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the filter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFilter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link EnvironmentvariableFilter }{@code >}
     * {@link JAXBElement }{@code <}{@link FilehashFilter }{@code >}
     * {@link JAXBElement }{@code <}{@link FamilyFilter }{@code >}
     * {@link JAXBElement }{@code <}{@link ProcessenvironmentFilter }{@code >}
     * {@link JAXBElement }{@code <}{@link VariableFilter }{@code >}
     * {@link JAXBElement }{@code <}{@link XmlfilecontentFilter }{@code >}
     * {@link JAXBElement }{@code <}{@link SqlFilter }{@code >}
     * {@link JAXBElement }{@code <}{@link FilterType }{@code >}
     * {@link JAXBElement }{@code <}{@link LdapFilter }{@code >}
     * {@link JAXBElement }{@code <}{@link TextfilecontentFilter }{@code >}
     * 
     * 
     */
    public List<JAXBElement<? extends FilterType>> getFilter() {
        if (filter == null) {
            filter = new ArrayList<JAXBElement<? extends FilterType>>();
        }
        return this.filter;
    }

}
