//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.20 at 09:27:07 AM EDT 
//

@javax.xml.bind.annotation.XmlSchema(
	namespace = "http://oval.cisecurity.org/XMLSchema/oval-system-characteristics-6#independent",
	elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
	xmlns = {
		//@XmlNs(prefix="", namespaceURI = "http://oval.cisecurity.org/XMLSchema/oval-system-characteristics-6#independent"),
		@XmlNs(prefix="ind-sc", namespaceURI = "http://oval.cisecurity.org/XMLSchema/oval-system-characteristics-6#independent")
	}
)
package org.cisecurity.oval.sc.ind;

import javax.xml.bind.annotation.XmlNs;