//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.21 at 11:38:58 AM EST 
//


package org.cisecurity.oval.sc.win;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.cisecurity.oval.sc.CollectedItemIntType;
import org.cisecurity.oval.sc.CollectedItemType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://oval.cisecurity.org/XMLSchema/oval-system-characteristics-6}CollectedItemType">
 *       &lt;sequence>
 *         &lt;element name="force_logoff" type="{http://oval.cisecurity.org/XMLSchema/oval-system-characteristics-6}CollectedItemIntType" minOccurs="0"/>
 *         &lt;element name="lockout_duration" type="{http://oval.cisecurity.org/XMLSchema/oval-system-characteristics-6}CollectedItemIntType" minOccurs="0"/>
 *         &lt;element name="lockout_observation_window" type="{http://oval.cisecurity.org/XMLSchema/oval-system-characteristics-6}CollectedItemIntType" minOccurs="0"/>
 *         &lt;element name="lockout_threshold" type="{http://oval.cisecurity.org/XMLSchema/oval-system-characteristics-6}CollectedItemIntType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "forceLogoff",
    "lockoutDuration",
    "lockoutObservationWindow",
    "lockoutThreshold"
})
public class LockoutpolicyItem
    extends CollectedItemType
{

    @XmlElement(name = "force_logoff")
    protected CollectedItemIntType forceLogoff;
    @XmlElement(name = "lockout_duration")
    protected CollectedItemIntType lockoutDuration;
    @XmlElement(name = "lockout_observation_window")
    protected CollectedItemIntType lockoutObservationWindow;
    @XmlElement(name = "lockout_threshold")
    protected CollectedItemIntType lockoutThreshold;

    /**
     * Gets the value of the forceLogoff property.
     * 
     * @return
     *     possible object is
     *     {@link CollectedItemIntType }
     *     
     */
    public CollectedItemIntType getForceLogoff() {
        return forceLogoff;
    }

    /**
     * Sets the value of the forceLogoff property.
     * 
     * @param value
     *     allowed object is
     *     {@link CollectedItemIntType }
     *     
     */
    public void setForceLogoff(CollectedItemIntType value) {
        this.forceLogoff = value;
    }

    /**
     * Gets the value of the lockoutDuration property.
     * 
     * @return
     *     possible object is
     *     {@link CollectedItemIntType }
     *     
     */
    public CollectedItemIntType getLockoutDuration() {
        return lockoutDuration;
    }

    /**
     * Sets the value of the lockoutDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link CollectedItemIntType }
     *     
     */
    public void setLockoutDuration(CollectedItemIntType value) {
        this.lockoutDuration = value;
    }

    /**
     * Gets the value of the lockoutObservationWindow property.
     * 
     * @return
     *     possible object is
     *     {@link CollectedItemIntType }
     *     
     */
    public CollectedItemIntType getLockoutObservationWindow() {
        return lockoutObservationWindow;
    }

    /**
     * Sets the value of the lockoutObservationWindow property.
     * 
     * @param value
     *     allowed object is
     *     {@link CollectedItemIntType }
     *     
     */
    public void setLockoutObservationWindow(CollectedItemIntType value) {
        this.lockoutObservationWindow = value;
    }

    /**
     * Gets the value of the lockoutThreshold property.
     * 
     * @return
     *     possible object is
     *     {@link CollectedItemIntType }
     *     
     */
    public CollectedItemIntType getLockoutThreshold() {
        return lockoutThreshold;
    }

    /**
     * Sets the value of the lockoutThreshold property.
     * 
     * @param value
     *     allowed object is
     *     {@link CollectedItemIntType }
     *     
     */
    public void setLockoutThreshold(CollectedItemIntType value) {
        this.lockoutThreshold = value;
    }

}
