//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.21 at 11:38:58 AM EST 
//


package org.cisecurity.oval.sc.win;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import org.cisecurity.oval.sc.CollectedItemAnySimpleType;
import org.cisecurity.oval.sc.CollectedItemIntType;
import org.cisecurity.oval.sc.CollectedItemStringType;
import org.cisecurity.oval.sc.CollectedItemType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://oval.cisecurity.org/XMLSchema/oval-system-characteristics-6}CollectedItemType">
 *       &lt;sequence>
 *         &lt;element name="hive" type="{http://oval.cisecurity.org/XMLSchema/oval-system-characteristics-6#windows}EntityItemRegistryHiveType" minOccurs="0"/>
 *         &lt;element name="key" type="{http://oval.cisecurity.org/XMLSchema/oval-system-characteristics-6}CollectedItemStringType" minOccurs="0"/>
 *         &lt;element name="name" type="{http://oval.cisecurity.org/XMLSchema/oval-system-characteristics-6}CollectedItemStringType" minOccurs="0"/>
 *         &lt;element name="last_write_time" type="{http://oval.cisecurity.org/XMLSchema/oval-system-characteristics-6}CollectedItemIntType" minOccurs="0"/>
 *         &lt;element name="type" type="{http://oval.cisecurity.org/XMLSchema/oval-system-characteristics-6#windows}EntityItemRegistryTypeType" minOccurs="0"/>
 *         &lt;element name="value" type="{http://oval.cisecurity.org/XMLSchema/oval-system-characteristics-6}CollectedItemAnySimpleType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="expanded_value" type="{http://oval.cisecurity.org/XMLSchema/oval-system-characteristics-6}CollectedItemAnySimpleType" minOccurs="0"/>
 *         &lt;element name="windows_view" type="{http://oval.cisecurity.org/XMLSchema/oval-system-characteristics-6#windows}EntityItemWindowsViewType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "hive",
    "key",
    "name",
    "lastWriteTime",
    "type",
    "value",
    "expandedValue",
    "windowsView"
})
public class RegistryItem
    extends CollectedItemType
{

    protected EntityItemRegistryHiveType hive;
    @XmlElementRef(name = "key", namespace = "http://oval.cisecurity.org/XMLSchema/oval-system-characteristics-6#windows", type = JAXBElement.class, required = false)
    protected JAXBElement<CollectedItemStringType> key;
    @XmlElementRef(name = "name", namespace = "http://oval.cisecurity.org/XMLSchema/oval-system-characteristics-6#windows", type = JAXBElement.class, required = false)
    protected JAXBElement<CollectedItemStringType> name;
    @XmlElement(name = "last_write_time")
    protected CollectedItemIntType lastWriteTime;
    protected EntityItemRegistryTypeType type;
    protected List<CollectedItemAnySimpleType> value;
    @XmlElement(name = "expanded_value")
    protected CollectedItemAnySimpleType expandedValue;
    @XmlElement(name = "windows_view")
    protected EntityItemWindowsViewType windowsView;

    /**
     * Gets the value of the hive property.
     * 
     * @return
     *     possible object is
     *     {@link EntityItemRegistryHiveType }
     *     
     */
    public EntityItemRegistryHiveType getHive() {
        return hive;
    }

    /**
     * Sets the value of the hive property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityItemRegistryHiveType }
     *     
     */
    public void setHive(EntityItemRegistryHiveType value) {
        this.hive = value;
    }

    /**
     * Gets the value of the key property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link CollectedItemStringType }{@code >}
     *     
     */
    public JAXBElement<CollectedItemStringType> getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link CollectedItemStringType }{@code >}
     *     
     */
    public void setKey(JAXBElement<CollectedItemStringType> value) {
        this.key = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link CollectedItemStringType }{@code >}
     *     
     */
    public JAXBElement<CollectedItemStringType> getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link CollectedItemStringType }{@code >}
     *     
     */
    public void setName(JAXBElement<CollectedItemStringType> value) {
        this.name = value;
    }

    /**
     * Gets the value of the lastWriteTime property.
     * 
     * @return
     *     possible object is
     *     {@link CollectedItemIntType }
     *     
     */
    public CollectedItemIntType getLastWriteTime() {
        return lastWriteTime;
    }

    /**
     * Sets the value of the lastWriteTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link CollectedItemIntType }
     *     
     */
    public void setLastWriteTime(CollectedItemIntType value) {
        this.lastWriteTime = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link EntityItemRegistryTypeType }
     *     
     */
    public EntityItemRegistryTypeType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityItemRegistryTypeType }
     *     
     */
    public void setType(EntityItemRegistryTypeType value) {
        this.type = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the value property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CollectedItemAnySimpleType }
     * 
     * 
     */
    public List<CollectedItemAnySimpleType> getValue() {
        if (value == null) {
            value = new ArrayList<CollectedItemAnySimpleType>();
        }
        return this.value;
    }

    /**
     * Gets the value of the expandedValue property.
     * 
     * @return
     *     possible object is
     *     {@link CollectedItemAnySimpleType }
     *     
     */
    public CollectedItemAnySimpleType getExpandedValue() {
        return expandedValue;
    }

    /**
     * Sets the value of the expandedValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link CollectedItemAnySimpleType }
     *     
     */
    public void setExpandedValue(CollectedItemAnySimpleType value) {
        this.expandedValue = value;
    }

    /**
     * Gets the value of the windowsView property.
     * 
     * @return
     *     possible object is
     *     {@link EntityItemWindowsViewType }
     *     
     */
    public EntityItemWindowsViewType getWindowsView() {
        return windowsView;
    }

    /**
     * Sets the value of the windowsView property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityItemWindowsViewType }
     *     
     */
    public void setWindowsView(EntityItemWindowsViewType value) {
        this.windowsView = value;
    }

}
