//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.21 at 11:38:45 AM EST 
//


package org.cisecurity.oval.collection.win;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.cisecurity.oval.collection.FilterAnySimpleType;
import org.cisecurity.oval.collection.FilterStringType;
import org.cisecurity.oval.collection.FilterType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://oval.cisecurity.org/XMLSchema/oval-collections-6}FilterType">
 *       &lt;sequence>
 *         &lt;element name="naming_context" type="{http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows}FilterNamingContextType" minOccurs="0"/>
 *         &lt;element name="relative_dn" type="{http://oval.cisecurity.org/XMLSchema/oval-collections-6}FilterStringType" minOccurs="0"/>
 *         &lt;element name="attribute" type="{http://oval.cisecurity.org/XMLSchema/oval-collections-6}FilterStringType" minOccurs="0"/>
 *         &lt;element name="object_class" type="{http://oval.cisecurity.org/XMLSchema/oval-collections-6}FilterStringType" minOccurs="0"/>
 *         &lt;element name="adstype" type="{http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows}FilterAdstypeType" minOccurs="0"/>
 *         &lt;element name="value" type="{http://oval.cisecurity.org/XMLSchema/oval-collections-6}FilterAnySimpleType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "namingContext",
    "relativeDn",
    "attribute",
    "objectClass",
    "adstype",
    "value"
})
public class ActivedirectoryFilter
    extends FilterType
{

    @XmlElement(name = "naming_context")
    protected FilterNamingContextType namingContext;
    @XmlElement(name = "relative_dn")
    protected FilterStringType relativeDn;
    protected FilterStringType attribute;
    @XmlElement(name = "object_class")
    protected FilterStringType objectClass;
    protected FilterAdstypeType adstype;
    protected FilterAnySimpleType value;

    /**
     * Gets the value of the namingContext property.
     * 
     * @return
     *     possible object is
     *     {@link FilterNamingContextType }
     *     
     */
    public FilterNamingContextType getNamingContext() {
        return namingContext;
    }

    /**
     * Sets the value of the namingContext property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterNamingContextType }
     *     
     */
    public void setNamingContext(FilterNamingContextType value) {
        this.namingContext = value;
    }

    /**
     * Gets the value of the relativeDn property.
     * 
     * @return
     *     possible object is
     *     {@link FilterStringType }
     *     
     */
    public FilterStringType getRelativeDn() {
        return relativeDn;
    }

    /**
     * Sets the value of the relativeDn property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterStringType }
     *     
     */
    public void setRelativeDn(FilterStringType value) {
        this.relativeDn = value;
    }

    /**
     * Gets the value of the attribute property.
     * 
     * @return
     *     possible object is
     *     {@link FilterStringType }
     *     
     */
    public FilterStringType getAttribute() {
        return attribute;
    }

    /**
     * Sets the value of the attribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterStringType }
     *     
     */
    public void setAttribute(FilterStringType value) {
        this.attribute = value;
    }

    /**
     * Gets the value of the objectClass property.
     * 
     * @return
     *     possible object is
     *     {@link FilterStringType }
     *     
     */
    public FilterStringType getObjectClass() {
        return objectClass;
    }

    /**
     * Sets the value of the objectClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterStringType }
     *     
     */
    public void setObjectClass(FilterStringType value) {
        this.objectClass = value;
    }

    /**
     * Gets the value of the adstype property.
     * 
     * @return
     *     possible object is
     *     {@link FilterAdstypeType }
     *     
     */
    public FilterAdstypeType getAdstype() {
        return adstype;
    }

    /**
     * Sets the value of the adstype property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterAdstypeType }
     *     
     */
    public void setAdstype(FilterAdstypeType value) {
        this.adstype = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link FilterAnySimpleType }
     *     
     */
    public FilterAnySimpleType getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterAnySimpleType }
     *     
     */
    public void setValue(FilterAnySimpleType value) {
        this.value = value;
    }

}
