//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.21 at 11:38:45 AM EST 
//


package org.cisecurity.oval.collection.win;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.cisecurity.oval.collection.FilterRecordType;
import org.cisecurity.oval.collection.FilterStringType;
import org.cisecurity.oval.collection.FilterType;
import org.cisecurity.oval.collection.FilterVersionType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://oval.cisecurity.org/XMLSchema/oval-collections-6}FilterType">
 *       &lt;sequence>
 *         &lt;element name="module_name" type="{http://oval.cisecurity.org/XMLSchema/oval-collections-6}FilterStringType" minOccurs="0"/>
 *         &lt;element name="module_id" type="{http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows}FilterGUIDType" minOccurs="0"/>
 *         &lt;element name="module_version" type="{http://oval.cisecurity.org/XMLSchema/oval-collections-6}FilterVersionType" minOccurs="0"/>
 *         &lt;element name="verb" type="{http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows}FilterCmdletVerbType" minOccurs="0"/>
 *         &lt;element name="noun" type="{http://oval.cisecurity.org/XMLSchema/oval-collections-6}FilterStringType" minOccurs="0"/>
 *         &lt;element name="parameters" type="{http://oval.cisecurity.org/XMLSchema/oval-collections-6}FilterRecordType" minOccurs="0"/>
 *         &lt;element name="select" type="{http://oval.cisecurity.org/XMLSchema/oval-collections-6}FilterRecordType" minOccurs="0"/>
 *         &lt;element name="value" type="{http://oval.cisecurity.org/XMLSchema/oval-collections-6}FilterRecordType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "moduleName",
    "moduleId",
    "moduleVersion",
    "verb",
    "noun",
    "parameters",
    "select",
    "value"
})
public class CmdletFilter
    extends FilterType
{

    @XmlElement(name = "module_name")
    protected FilterStringType moduleName;
    @XmlElement(name = "module_id")
    protected FilterGUIDType moduleId;
    @XmlElement(name = "module_version")
    protected FilterVersionType moduleVersion;
    protected FilterCmdletVerbType verb;
    protected FilterStringType noun;
    protected FilterRecordType parameters;
    protected FilterRecordType select;
    protected FilterRecordType value;

    /**
     * Gets the value of the moduleName property.
     * 
     * @return
     *     possible object is
     *     {@link FilterStringType }
     *     
     */
    public FilterStringType getModuleName() {
        return moduleName;
    }

    /**
     * Sets the value of the moduleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterStringType }
     *     
     */
    public void setModuleName(FilterStringType value) {
        this.moduleName = value;
    }

    /**
     * Gets the value of the moduleId property.
     * 
     * @return
     *     possible object is
     *     {@link FilterGUIDType }
     *     
     */
    public FilterGUIDType getModuleId() {
        return moduleId;
    }

    /**
     * Sets the value of the moduleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterGUIDType }
     *     
     */
    public void setModuleId(FilterGUIDType value) {
        this.moduleId = value;
    }

    /**
     * Gets the value of the moduleVersion property.
     * 
     * @return
     *     possible object is
     *     {@link FilterVersionType }
     *     
     */
    public FilterVersionType getModuleVersion() {
        return moduleVersion;
    }

    /**
     * Sets the value of the moduleVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterVersionType }
     *     
     */
    public void setModuleVersion(FilterVersionType value) {
        this.moduleVersion = value;
    }

    /**
     * Gets the value of the verb property.
     * 
     * @return
     *     possible object is
     *     {@link FilterCmdletVerbType }
     *     
     */
    public FilterCmdletVerbType getVerb() {
        return verb;
    }

    /**
     * Sets the value of the verb property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterCmdletVerbType }
     *     
     */
    public void setVerb(FilterCmdletVerbType value) {
        this.verb = value;
    }

    /**
     * Gets the value of the noun property.
     * 
     * @return
     *     possible object is
     *     {@link FilterStringType }
     *     
     */
    public FilterStringType getNoun() {
        return noun;
    }

    /**
     * Sets the value of the noun property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterStringType }
     *     
     */
    public void setNoun(FilterStringType value) {
        this.noun = value;
    }

    /**
     * Gets the value of the parameters property.
     * 
     * @return
     *     possible object is
     *     {@link FilterRecordType }
     *     
     */
    public FilterRecordType getParameters() {
        return parameters;
    }

    /**
     * Sets the value of the parameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterRecordType }
     *     
     */
    public void setParameters(FilterRecordType value) {
        this.parameters = value;
    }

    /**
     * Gets the value of the select property.
     * 
     * @return
     *     possible object is
     *     {@link FilterRecordType }
     *     
     */
    public FilterRecordType getSelect() {
        return select;
    }

    /**
     * Sets the value of the select property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterRecordType }
     *     
     */
    public void setSelect(FilterRecordType value) {
        this.select = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link FilterRecordType }
     *     
     */
    public FilterRecordType getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterRecordType }
     *     
     */
    public void setValue(FilterRecordType value) {
        this.value = value;
    }

}
