//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.21 at 11:38:45 AM EST 
//


package org.cisecurity.oval.collection.win;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import org.cisecurity.oval.collection.FilterType;
import org.cisecurity.oval.collection.ObjectIntType;
import org.cisecurity.oval.collection.ObjectRecordType;
import org.cisecurity.oval.collection.ObjectStringType;
import org.cisecurity.oval.collection.ObjectType;
import org.cisecurity.oval.collection.ObjectVersionType;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.cisecurity.oval.collection.win package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GroupSidFilter_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "group_sid_filter");
    private final static QName _MetabaseObject_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "metabase_object");
    private final static QName _PasswordpolicyFilter_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "passwordpolicy_filter");
    private final static QName _RegkeyeffectiverightsObject_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "regkeyeffectiverights_object");
//    private final static QName _Object_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6", "object");
    private final static QName _DnscacheFilter_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "dnscache_filter");
    private final static QName _UserrightObject_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "userright_object");
    private final static QName _ServiceeffectiverightsObject_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "serviceeffectiverights_object");
    private final static QName _JunctionObject_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "junction_object");
    private final static QName _AuditeventpolicyFilter_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "auditeventpolicy_filter");
    private final static QName _RegkeyauditedpermissionsObject_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "regkeyauditedpermissions_object");
    private final static QName _Wmi57Filter_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "wmi57_filter");
    private final static QName _GroupFilter_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "group_filter");
    private final static QName _PrintereffectiverightsObject_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "printereffectiverights_object");
    private final static QName _ActivedirectoryFilter_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "activedirectory_filter");
    private final static QName _SharedresourceFilter_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "sharedresource_filter");
    private final static QName _SharedresourceauditedpermissionsObject_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "sharedresourceauditedpermissions_object");
    private final static QName _VolumeFilter_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "volume_filter");
    private final static QName _FileeffectiverightsObject_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "fileeffectiverights_object");
    private final static QName _WuaupdatesearcherObject_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "wuaupdatesearcher_object");
    private final static QName _FileauditedpermissionsObject_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "fileauditedpermissions_object");
    private final static QName _SystemmetricObject_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "systemmetric_object");
    private final static QName _GroupSidObject_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "group_sid_object");
    private final static QName _LicenseFilter_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "license_filter");
    private final static QName _ActivedirectoryObject_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "activedirectory_object");
    private final static QName _LockoutpolicyObject_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "lockoutpolicy_object");
    private final static QName _NtuserFilter_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "ntuser_filter");
    private final static QName _UacFilter_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "uac_filter");
    private final static QName _PortObject_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "port_object");
    private final static QName _SharedresourceauditedpermissionsFilter_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "sharedresourceauditedpermissions_filter");
    private final static QName _VolumeObject_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "volume_object");
    private final static QName _ServiceFilter_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "service_filter");
    private final static QName _SharedresourceeffectiverightsObject_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "sharedresourceeffectiverights_object");
    private final static QName _ProcessFilter_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "process_filter");
    private final static QName _AuditeventpolicysubcategoriesObject_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "auditeventpolicysubcategories_object");
    private final static QName _SidFilter_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "sid_filter");
    private final static QName _CmdletFilter_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "cmdlet_filter");
    private final static QName _FileFilter_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "file_filter");
    private final static QName _UserSid55Filter_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "user_sid55_filter");
    private final static QName _DnscacheObject_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "dnscache_object");
    private final static QName _SidSidObject_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "sid_sid_object");
    private final static QName _PeheaderFilter_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "peheader_filter");
    private final static QName _MetabaseFilter_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "metabase_filter");
    private final static QName _UserObject_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "user_object");
    private final static QName _PrintereffectiverightsFilter_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "printereffectiverights_filter");
    private final static QName _SidSidFilter_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "sid_sid_filter");
    private final static QName _UserSid55Object_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "user_sid55_object");
    private final static QName _CmdletObject_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "cmdlet_object");
    private final static QName _FileObject_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "file_object");
    private final static QName _Wmi57Object_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "wmi57_object");
    private final static QName _FileeffectiverightsFilter_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "fileeffectiverights_filter");
    private final static QName _SharedresourceObject_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "sharedresource_object");
    private final static QName _PeheaderObject_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "peheader_object");
    private final static QName _InterfaceObject_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "interface_object");
    private final static QName _InterfaceFilter_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "interface_filter");
    private final static QName _ServiceeffectiverightsFilter_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "serviceeffectiverights_filter");
    private final static QName _JunctionFilter_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "junction_filter");
    private final static QName _UserrightFilter_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "userright_filter");
    private final static QName _RegkeyauditedpermissionsFilter_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "regkeyauditedpermissions_filter");
    private final static QName _AuditeventpolicyObject_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "auditeventpolicy_object");
    private final static QName _GroupObject_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "group_object");
    private final static QName _RegistryFilter_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "registry_filter");
    private final static QName _PasswordpolicyObject_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "passwordpolicy_object");
    private final static QName _PortFilter_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "port_filter");
    private final static QName _RegkeyeffectiverightsFilter_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "regkeyeffectiverights_filter");
    private final static QName _FileauditedpermissionsFilter_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "fileauditedpermissions_filter");
    private final static QName _LicenseObject_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "license_object");
    private final static QName _UserFilter_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "user_filter");
    private final static QName _WuaupdatesearcherFilter_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "wuaupdatesearcher_filter");
    private final static QName _NtuserObject_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "ntuser_object");
    private final static QName _LockoutpolicyFilter_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "lockoutpolicy_filter");
    private final static QName _SidObject_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "sid_object");
    private final static QName _UacObject_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "uac_object");
    private final static QName _ProcessObject_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "process_object");
    private final static QName _RegistryObject_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "registry_object");
    private final static QName _SystemmetricFilter_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "systemmetric_filter");
    private final static QName _AuditeventpolicysubcategoriesFilter_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "auditeventpolicysubcategories_filter");
    private final static QName _ServiceObject_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "service_object");
    private final static QName _SharedresourceeffectiverightsFilter_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "sharedresourceeffectiverights_filter");
//    private final static QName _ItemFilter_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6", "item_filter");
    private final static QName _FileeffectiverightsObjectFilename_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "filename");
    private final static QName _RegkeyeffectiverightsObjectKey_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "key");
    private final static QName _MetabaseObjectId_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "id");
    private final static QName _NtuserObjectName_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "name");
    private final static QName _ActivedirectoryObjectAttribute_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "attribute");
    private final static QName _ActivedirectoryObjectRelativeDn_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "relative_dn");
    private final static QName _ProcessObjectCommandLine_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "command_line");
    private final static QName _CmdletObjectParameters_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "parameters");
    private final static QName _CmdletObjectModuleVersion_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "module_version");
    private final static QName _CmdletObjectModuleName_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "module_name");
    private final static QName _CmdletObjectModuleId_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "module_id");
    private final static QName _CmdletObjectSelect_QNAME = new QName("http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", "select");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.cisecurity.oval.collection.win
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ProcessFilter }
     * 
     */
    public ProcessFilter createProcessFilter() {
        return new ProcessFilter();
    }

    /**
     * Create an instance of {@link FileFilter }
     * 
     */
    public FileFilter createFileFilter() {
        return new FileFilter();
    }

    /**
     * Create an instance of {@link FileeffectiverightsFilter }
     * 
     */
    public FileeffectiverightsFilter createFileeffectiverightsFilter() {
        return new FileeffectiverightsFilter();
    }

    /**
     * Create an instance of {@link SharedresourceObject }
     * 
     */
    public SharedresourceObject createSharedresourceObject() {
        return new SharedresourceObject();
    }

    /**
     * Create an instance of {@link PeheaderObject }
     * 
     */
    public PeheaderObject createPeheaderObject() {
        return new PeheaderObject();
    }

    /**
     * Create an instance of {@link CmdletObject }
     * 
     */
    public CmdletObject createCmdletObject() {
        return new CmdletObject();
    }

    /**
     * Create an instance of {@link PrintereffectiverightsFilter }
     * 
     */
    public PrintereffectiverightsFilter createPrintereffectiverightsFilter() {
        return new PrintereffectiverightsFilter();
    }

    /**
     * Create an instance of {@link SidSidFilter }
     * 
     */
    public SidSidFilter createSidSidFilter() {
        return new SidSidFilter();
    }

    /**
     * Create an instance of {@link UserSid55Object }
     * 
     */
    public UserSid55Object createUserSid55Object() {
        return new UserSid55Object();
    }

    /**
     * Create an instance of {@link FileObject }
     * 
     */
    public FileObject createFileObject() {
        return new FileObject();
    }

    /**
     * Create an instance of {@link Wmi57Object }
     * 
     */
    public Wmi57Object createWmi57Object() {
        return new Wmi57Object();
    }

    /**
     * Create an instance of {@link MetabaseFilter }
     * 
     */
    public MetabaseFilter createMetabaseFilter() {
        return new MetabaseFilter();
    }

    /**
     * Create an instance of {@link UserObject }
     * 
     */
    public UserObject createUserObject() {
        return new UserObject();
    }

    /**
     * Create an instance of {@link RegkeyeffectiverightsFilter }
     * 
     */
    public RegkeyeffectiverightsFilter createRegkeyeffectiverightsFilter() {
        return new RegkeyeffectiverightsFilter();
    }

    /**
     * Create an instance of {@link RegistryFilter }
     * 
     */
    public RegistryFilter createRegistryFilter() {
        return new RegistryFilter();
    }

    /**
     * Create an instance of {@link PasswordpolicyObject }
     * 
     */
    public PasswordpolicyObject createPasswordpolicyObject() {
        return new PasswordpolicyObject();
    }

    /**
     * Create an instance of {@link PortFilter }
     * 
     */
    public PortFilter createPortFilter() {
        return new PortFilter();
    }

    /**
     * Create an instance of {@link RegkeyauditedpermissionsFilter }
     * 
     */
    public RegkeyauditedpermissionsFilter createRegkeyauditedpermissionsFilter() {
        return new RegkeyauditedpermissionsFilter();
    }

    /**
     * Create an instance of {@link AuditeventpolicyObject }
     * 
     */
    public AuditeventpolicyObject createAuditeventpolicyObject() {
        return new AuditeventpolicyObject();
    }

    /**
     * Create an instance of {@link GroupObject }
     * 
     */
    public GroupObject createGroupObject() {
        return new GroupObject();
    }

    /**
     * Create an instance of {@link InterfaceObject }
     * 
     */
    public InterfaceObject createInterfaceObject() {
        return new InterfaceObject();
    }

    /**
     * Create an instance of {@link JunctionFilter }
     * 
     */
    public JunctionFilter createJunctionFilter() {
        return new JunctionFilter();
    }

    /**
     * Create an instance of {@link UserrightFilter }
     * 
     */
    public UserrightFilter createUserrightFilter() {
        return new UserrightFilter();
    }

    /**
     * Create an instance of {@link InterfaceFilter }
     * 
     */
    public InterfaceFilter createInterfaceFilter() {
        return new InterfaceFilter();
    }

    /**
     * Create an instance of {@link ServiceeffectiverightsFilter }
     * 
     */
    public ServiceeffectiverightsFilter createServiceeffectiverightsFilter() {
        return new ServiceeffectiverightsFilter();
    }

    /**
     * Create an instance of {@link SystemmetricFilter }
     * 
     */
    public SystemmetricFilter createSystemmetricFilter() {
        return new SystemmetricFilter();
    }

    /**
     * Create an instance of {@link UacObject }
     * 
     */
    public UacObject createUacObject() {
        return new UacObject();
    }

    /**
     * Create an instance of {@link SidObject }
     * 
     */
    public SidObject createSidObject() {
        return new SidObject();
    }

    /**
     * Create an instance of {@link ProcessObject }
     * 
     */
    public ProcessObject createProcessObject() {
        return new ProcessObject();
    }

    /**
     * Create an instance of {@link RegistryObject }
     * 
     */
    public RegistryObject createRegistryObject() {
        return new RegistryObject();
    }

    /**
     * Create an instance of {@link NtuserObject }
     * 
     */
    public NtuserObject createNtuserObject() {
        return new NtuserObject();
    }

    /**
     * Create an instance of {@link LockoutpolicyFilter }
     * 
     */
    public LockoutpolicyFilter createLockoutpolicyFilter() {
        return new LockoutpolicyFilter();
    }

    /**
     * Create an instance of {@link FileauditedpermissionsFilter }
     * 
     */
    public FileauditedpermissionsFilter createFileauditedpermissionsFilter() {
        return new FileauditedpermissionsFilter();
    }

    /**
     * Create an instance of {@link LicenseObject }
     * 
     */
    public LicenseObject createLicenseObject() {
        return new LicenseObject();
    }

    /**
     * Create an instance of {@link UserFilter }
     * 
     */
    public UserFilter createUserFilter() {
        return new UserFilter();
    }

    /**
     * Create an instance of {@link WuaupdatesearcherFilter }
     * 
     */
    public WuaupdatesearcherFilter createWuaupdatesearcherFilter() {
        return new WuaupdatesearcherFilter();
    }

    /**
     * Create an instance of {@link AuditeventpolicysubcategoriesFilter }
     * 
     */
    public AuditeventpolicysubcategoriesFilter createAuditeventpolicysubcategoriesFilter() {
        return new AuditeventpolicysubcategoriesFilter();
    }

    /**
     * Create an instance of {@link SharedresourceeffectiverightsFilter }
     * 
     */
    public SharedresourceeffectiverightsFilter createSharedresourceeffectiverightsFilter() {
        return new SharedresourceeffectiverightsFilter();
    }

    /**
     * Create an instance of {@link ServiceObject }
     * 
     */
    public ServiceObject createServiceObject() {
        return new ServiceObject();
    }

    /**
     * Create an instance of {@link DnscacheFilter }
     * 
     */
    public DnscacheFilter createDnscacheFilter() {
        return new DnscacheFilter();
    }

    /**
     * Create an instance of {@link PasswordpolicyFilter }
     * 
     */
    public PasswordpolicyFilter createPasswordpolicyFilter() {
        return new PasswordpolicyFilter();
    }

    /**
     * Create an instance of {@link RegkeyeffectiverightsObject }
     * 
     */
    public RegkeyeffectiverightsObject createRegkeyeffectiverightsObject() {
        return new RegkeyeffectiverightsObject();
    }

    /**
     * Create an instance of {@link MetabaseObject }
     * 
     */
    public MetabaseObject createMetabaseObject() {
        return new MetabaseObject();
    }

    /**
     * Create an instance of {@link GroupSidFilter }
     * 
     */
    public GroupSidFilter createGroupSidFilter() {
        return new GroupSidFilter();
    }

    /**
     * Create an instance of {@link FileeffectiverightsObject }
     * 
     */
    public FileeffectiverightsObject createFileeffectiverightsObject() {
        return new FileeffectiverightsObject();
    }

    /**
     * Create an instance of {@link GroupFilter }
     * 
     */
    public GroupFilter createGroupFilter() {
        return new GroupFilter();
    }

    /**
     * Create an instance of {@link PrintereffectiverightsObject }
     * 
     */
    public PrintereffectiverightsObject createPrintereffectiverightsObject() {
        return new PrintereffectiverightsObject();
    }

    /**
     * Create an instance of {@link Wmi57Filter }
     * 
     */
    public Wmi57Filter createWmi57Filter() {
        return new Wmi57Filter();
    }

    /**
     * Create an instance of {@link ActivedirectoryFilter }
     * 
     */
    public ActivedirectoryFilter createActivedirectoryFilter() {
        return new ActivedirectoryFilter();
    }

    /**
     * Create an instance of {@link SharedresourceFilter }
     * 
     */
    public SharedresourceFilter createSharedresourceFilter() {
        return new SharedresourceFilter();
    }

    /**
     * Create an instance of {@link SharedresourceauditedpermissionsObject }
     * 
     */
    public SharedresourceauditedpermissionsObject createSharedresourceauditedpermissionsObject() {
        return new SharedresourceauditedpermissionsObject();
    }

    /**
     * Create an instance of {@link VolumeFilter }
     * 
     */
    public VolumeFilter createVolumeFilter() {
        return new VolumeFilter();
    }

    /**
     * Create an instance of {@link AuditeventpolicyFilter }
     * 
     */
    public AuditeventpolicyFilter createAuditeventpolicyFilter() {
        return new AuditeventpolicyFilter();
    }

    /**
     * Create an instance of {@link RegkeyauditedpermissionsObject }
     * 
     */
    public RegkeyauditedpermissionsObject createRegkeyauditedpermissionsObject() {
        return new RegkeyauditedpermissionsObject();
    }

    /**
     * Create an instance of {@link ServiceeffectiverightsObject }
     * 
     */
    public ServiceeffectiverightsObject createServiceeffectiverightsObject() {
        return new ServiceeffectiverightsObject();
    }

    /**
     * Create an instance of {@link UserrightObject }
     * 
     */
    public UserrightObject createUserrightObject() {
        return new UserrightObject();
    }

    /**
     * Create an instance of {@link JunctionObject }
     * 
     */
    public JunctionObject createJunctionObject() {
        return new JunctionObject();
    }

    /**
     * Create an instance of {@link SharedresourceauditedpermissionsFilter }
     * 
     */
    public SharedresourceauditedpermissionsFilter createSharedresourceauditedpermissionsFilter() {
        return new SharedresourceauditedpermissionsFilter();
    }

    /**
     * Create an instance of {@link PortObject }
     * 
     */
    public PortObject createPortObject() {
        return new PortObject();
    }

    /**
     * Create an instance of {@link VolumeObject }
     * 
     */
    public VolumeObject createVolumeObject() {
        return new VolumeObject();
    }

    /**
     * Create an instance of {@link ActivedirectoryObject }
     * 
     */
    public ActivedirectoryObject createActivedirectoryObject() {
        return new ActivedirectoryObject();
    }

    /**
     * Create an instance of {@link LockoutpolicyObject }
     * 
     */
    public LockoutpolicyObject createLockoutpolicyObject() {
        return new LockoutpolicyObject();
    }

    /**
     * Create an instance of {@link NtuserFilter }
     * 
     */
    public NtuserFilter createNtuserFilter() {
        return new NtuserFilter();
    }

    /**
     * Create an instance of {@link UacFilter }
     * 
     */
    public UacFilter createUacFilter() {
        return new UacFilter();
    }

    /**
     * Create an instance of {@link FileauditedpermissionsObject }
     * 
     */
    public FileauditedpermissionsObject createFileauditedpermissionsObject() {
        return new FileauditedpermissionsObject();
    }

    /**
     * Create an instance of {@link WuaupdatesearcherObject }
     * 
     */
    public WuaupdatesearcherObject createWuaupdatesearcherObject() {
        return new WuaupdatesearcherObject();
    }

    /**
     * Create an instance of {@link GroupSidObject }
     * 
     */
    public GroupSidObject createGroupSidObject() {
        return new GroupSidObject();
    }

    /**
     * Create an instance of {@link LicenseFilter }
     * 
     */
    public LicenseFilter createLicenseFilter() {
        return new LicenseFilter();
    }

    /**
     * Create an instance of {@link SystemmetricObject }
     * 
     */
    public SystemmetricObject createSystemmetricObject() {
        return new SystemmetricObject();
    }

    /**
     * Create an instance of {@link PeheaderFilter }
     * 
     */
    public PeheaderFilter createPeheaderFilter() {
        return new PeheaderFilter();
    }

    /**
     * Create an instance of {@link SidFilter }
     * 
     */
    public SidFilter createSidFilter() {
        return new SidFilter();
    }

    /**
     * Create an instance of {@link DnscacheObject }
     * 
     */
    public DnscacheObject createDnscacheObject() {
        return new DnscacheObject();
    }

    /**
     * Create an instance of {@link SidSidObject }
     * 
     */
    public SidSidObject createSidSidObject() {
        return new SidSidObject();
    }

    /**
     * Create an instance of {@link CmdletFilter }
     * 
     */
    public CmdletFilter createCmdletFilter() {
        return new CmdletFilter();
    }

    /**
     * Create an instance of {@link UserSid55Filter }
     * 
     */
    public UserSid55Filter createUserSid55Filter() {
        return new UserSid55Filter();
    }

    /**
     * Create an instance of {@link SharedresourceeffectiverightsObject }
     * 
     */
    public SharedresourceeffectiverightsObject createSharedresourceeffectiverightsObject() {
        return new SharedresourceeffectiverightsObject();
    }

    /**
     * Create an instance of {@link AuditeventpolicysubcategoriesObject }
     * 
     */
    public AuditeventpolicysubcategoriesObject createAuditeventpolicysubcategoriesObject() {
        return new AuditeventpolicysubcategoriesObject();
    }

    /**
     * Create an instance of {@link ServiceFilter }
     * 
     */
    public ServiceFilter createServiceFilter() {
        return new ServiceFilter();
    }

    /**
     * Create an instance of {@link FilterNTUserAccountTypeType }
     * 
     */
    public FilterNTUserAccountTypeType createFilterNTUserAccountTypeType() {
        return new FilterNTUserAccountTypeType();
    }

    /**
     * Create an instance of {@link FilterPeTargetMachineType }
     * 
     */
    public FilterPeTargetMachineType createFilterPeTargetMachineType() {
        return new FilterPeTargetMachineType();
    }

    /**
     * Create an instance of {@link FilterSharedResourceTypeType }
     * 
     */
    public FilterSharedResourceTypeType createFilterSharedResourceTypeType() {
        return new FilterSharedResourceTypeType();
    }

    /**
     * Create an instance of {@link FilterServiceControlsAcceptedType }
     * 
     */
    public FilterServiceControlsAcceptedType createFilterServiceControlsAcceptedType() {
        return new FilterServiceControlsAcceptedType();
    }

    /**
     * Create an instance of {@link PrinterEffectiveRightsBehaviors }
     * 
     */
    public PrinterEffectiveRightsBehaviors createPrinterEffectiveRightsBehaviors() {
        return new PrinterEffectiveRightsBehaviors();
    }

    /**
     * Create an instance of {@link FilterNamingContextType }
     * 
     */
    public FilterNamingContextType createFilterNamingContextType() {
        return new FilterNamingContextType();
    }

    /**
     * Create an instance of {@link RegkeyAuditPermissionsBehaviors }
     * 
     */
    public RegkeyAuditPermissionsBehaviors createRegkeyAuditPermissionsBehaviors() {
        return new RegkeyAuditPermissionsBehaviors();
    }

    /**
     * Create an instance of {@link RegkeyEffectiveRightsBehaviors }
     * 
     */
    public RegkeyEffectiveRightsBehaviors createRegkeyEffectiveRightsBehaviors() {
        return new RegkeyEffectiveRightsBehaviors();
    }

    /**
     * Create an instance of {@link SharedResourceEffectiveRightsBehaviors }
     * 
     */
    public SharedResourceEffectiveRightsBehaviors createSharedResourceEffectiveRightsBehaviors() {
        return new SharedResourceEffectiveRightsBehaviors();
    }

    /**
     * Create an instance of {@link FilterInterfaceTypeType }
     * 
     */
    public FilterInterfaceTypeType createFilterInterfaceTypeType() {
        return new FilterInterfaceTypeType();
    }

    /**
     * Create an instance of {@link FilterRegistryHiveType }
     * 
     */
    public FilterRegistryHiveType createFilterRegistryHiveType() {
        return new FilterRegistryHiveType();
    }

    /**
     * Create an instance of {@link RegistryBehaviors }
     * 
     */
    public RegistryBehaviors createRegistryBehaviors() {
        return new RegistryBehaviors();
    }

    /**
     * Create an instance of {@link ObjectCmdletVerbType }
     * 
     */
    public ObjectCmdletVerbType createObjectCmdletVerbType() {
        return new ObjectCmdletVerbType();
    }

    /**
     * Create an instance of {@link FileAuditPermissionsBehaviors }
     * 
     */
    public FileAuditPermissionsBehaviors createFileAuditPermissionsBehaviors() {
        return new FileAuditPermissionsBehaviors();
    }

    /**
     * Create an instance of {@link SidSidBehaviors }
     * 
     */
    public SidSidBehaviors createSidSidBehaviors() {
        return new SidSidBehaviors();
    }

    /**
     * Create an instance of {@link FilterDriveTypeType }
     * 
     */
    public FilterDriveTypeType createFilterDriveTypeType() {
        return new FilterDriveTypeType();
    }

    /**
     * Create an instance of {@link FilterPeSubsystemType }
     * 
     */
    public FilterPeSubsystemType createFilterPeSubsystemType() {
        return new FilterPeSubsystemType();
    }

    /**
     * Create an instance of {@link FilterAddrTypeType }
     * 
     */
    public FilterAddrTypeType createFilterAddrTypeType() {
        return new FilterAddrTypeType();
    }

    /**
     * Create an instance of {@link FilterServiceStartTypeType }
     * 
     */
    public FilterServiceStartTypeType createFilterServiceStartTypeType() {
        return new FilterServiceStartTypeType();
    }

    /**
     * Create an instance of {@link FilterCmdletVerbType }
     * 
     */
    public FilterCmdletVerbType createFilterCmdletVerbType() {
        return new FilterCmdletVerbType();
    }

    /**
     * Create an instance of {@link SidBehaviors }
     * 
     */
    public SidBehaviors createSidBehaviors() {
        return new SidBehaviors();
    }

    /**
     * Create an instance of {@link ObjectUserRightType }
     * 
     */
    public ObjectUserRightType createObjectUserRightType() {
        return new ObjectUserRightType();
    }

    /**
     * Create an instance of {@link FilterAdstypeType }
     * 
     */
    public FilterAdstypeType createFilterAdstypeType() {
        return new FilterAdstypeType();
    }

    /**
     * Create an instance of {@link FilterUserRightType }
     * 
     */
    public FilterUserRightType createFilterUserRightType() {
        return new FilterUserRightType();
    }

    /**
     * Create an instance of {@link ObjectRegistryHiveType }
     * 
     */
    public ObjectRegistryHiveType createObjectRegistryHiveType() {
        return new ObjectRegistryHiveType();
    }

    /**
     * Create an instance of {@link ObjectNamingContextType }
     * 
     */
    public ObjectNamingContextType createObjectNamingContextType() {
        return new ObjectNamingContextType();
    }

    /**
     * Create an instance of {@link FilterAuditType }
     * 
     */
    public FilterAuditType createFilterAuditType() {
        return new FilterAuditType();
    }

    /**
     * Create an instance of {@link NTUserBehaviors }
     * 
     */
    public NTUserBehaviors createNTUserBehaviors() {
        return new NTUserBehaviors();
    }

    /**
     * Create an instance of {@link FilterProtocolType }
     * 
     */
    public FilterProtocolType createFilterProtocolType() {
        return new FilterProtocolType();
    }

    /**
     * Create an instance of {@link ObjectGUIDType }
     * 
     */
    public ObjectGUIDType createObjectGUIDType() {
        return new ObjectGUIDType();
    }

    /**
     * Create an instance of {@link FilterRegistryTypeType }
     * 
     */
    public FilterRegistryTypeType createFilterRegistryTypeType() {
        return new FilterRegistryTypeType();
    }

    /**
     * Create an instance of {@link FilterFileTypeType }
     * 
     */
    public FilterFileTypeType createFilterFileTypeType() {
        return new FilterFileTypeType();
    }

    /**
     * Create an instance of {@link FilterFileAttributeType }
     * 
     */
    public FilterFileAttributeType createFilterFileAttributeType() {
        return new FilterFileAttributeType();
    }

    /**
     * Create an instance of {@link FilterSystemMetricIndexType }
     * 
     */
    public FilterSystemMetricIndexType createFilterSystemMetricIndexType() {
        return new FilterSystemMetricIndexType();
    }

    /**
     * Create an instance of {@link FileEffectiveRightsBehaviors }
     * 
     */
    public FileEffectiveRightsBehaviors createFileEffectiveRightsBehaviors() {
        return new FileEffectiveRightsBehaviors();
    }

    /**
     * Create an instance of {@link FilterServiceTypeType }
     * 
     */
    public FilterServiceTypeType createFilterServiceTypeType() {
        return new FilterServiceTypeType();
    }

    /**
     * Create an instance of {@link WuaUpdateSearcherBehaviors }
     * 
     */
    public WuaUpdateSearcherBehaviors createWuaUpdateSearcherBehaviors() {
        return new WuaUpdateSearcherBehaviors();
    }

    /**
     * Create an instance of {@link FileBehaviors }
     * 
     */
    public FileBehaviors createFileBehaviors() {
        return new FileBehaviors();
    }

    /**
     * Create an instance of {@link ServiceEffectiveRightsBehaviors }
     * 
     */
    public ServiceEffectiveRightsBehaviors createServiceEffectiveRightsBehaviors() {
        return new ServiceEffectiveRightsBehaviors();
    }

    /**
     * Create an instance of {@link ObjectProtocolType }
     * 
     */
    public ObjectProtocolType createObjectProtocolType() {
        return new ObjectProtocolType();
    }

    /**
     * Create an instance of {@link FilterWindowsViewType }
     * 
     */
    public FilterWindowsViewType createFilterWindowsViewType() {
        return new FilterWindowsViewType();
    }

    /**
     * Create an instance of {@link ObjectSystemMetricIndexType }
     * 
     */
    public ObjectSystemMetricIndexType createObjectSystemMetricIndexType() {
        return new ObjectSystemMetricIndexType();
    }

    /**
     * Create an instance of {@link SharedResourceAuditedPermissionsBehaviors }
     * 
     */
    public SharedResourceAuditedPermissionsBehaviors createSharedResourceAuditedPermissionsBehaviors() {
        return new SharedResourceAuditedPermissionsBehaviors();
    }

    /**
     * Create an instance of {@link FilterServiceCurrentStateType }
     * 
     */
    public FilterServiceCurrentStateType createFilterServiceCurrentStateType() {
        return new FilterServiceCurrentStateType();
    }

    /**
     * Create an instance of {@link FilterGUIDType }
     * 
     */
    public FilterGUIDType createFilterGUIDType() {
        return new FilterGUIDType();
    }

    /**
     * Create an instance of {@link ProcessFilter.Priority }
     * 
     */
    public ProcessFilter.Priority createProcessFilterPriority() {
        return new ProcessFilter.Priority();
    }

    /**
     * Create an instance of {@link FileFilter.ProductVersion }
     * 
     */
    public FileFilter.ProductVersion createFileFilterProductVersion() {
        return new FileFilter.ProductVersion();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GroupSidFilter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "group_sid_filter", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "item_filter")
    public JAXBElement<GroupSidFilter> createGroupSidFilter(GroupSidFilter value) {
        return new JAXBElement<GroupSidFilter>(_GroupSidFilter_QNAME, GroupSidFilter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MetabaseObject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "metabase_object", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "object")
    public JAXBElement<MetabaseObject> createMetabaseObject(MetabaseObject value) {
        return new JAXBElement<MetabaseObject>(_MetabaseObject_QNAME, MetabaseObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PasswordpolicyFilter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "passwordpolicy_filter", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "item_filter")
    public JAXBElement<PasswordpolicyFilter> createPasswordpolicyFilter(PasswordpolicyFilter value) {
        return new JAXBElement<PasswordpolicyFilter>(_PasswordpolicyFilter_QNAME, PasswordpolicyFilter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegkeyeffectiverightsObject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "regkeyeffectiverights_object", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "object")
    public JAXBElement<RegkeyeffectiverightsObject> createRegkeyeffectiverightsObject(RegkeyeffectiverightsObject value) {
        return new JAXBElement<RegkeyeffectiverightsObject>(_RegkeyeffectiverightsObject_QNAME, RegkeyeffectiverightsObject.class, null, value);
    }

//    /**
//     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectType }{@code >}}
//     *
//     */
//    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", name = "object")
//    public JAXBElement<ObjectType> createObject(ObjectType value) {
//        return new JAXBElement<ObjectType>(_Object_QNAME, ObjectType.class, null, value);
//    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DnscacheFilter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "dnscache_filter", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "item_filter")
    public JAXBElement<DnscacheFilter> createDnscacheFilter(DnscacheFilter value) {
        return new JAXBElement<DnscacheFilter>(_DnscacheFilter_QNAME, DnscacheFilter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserrightObject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "userright_object", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "object")
    public JAXBElement<UserrightObject> createUserrightObject(UserrightObject value) {
        return new JAXBElement<UserrightObject>(_UserrightObject_QNAME, UserrightObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceeffectiverightsObject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "serviceeffectiverights_object", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "object")
    public JAXBElement<ServiceeffectiverightsObject> createServiceeffectiverightsObject(ServiceeffectiverightsObject value) {
        return new JAXBElement<ServiceeffectiverightsObject>(_ServiceeffectiverightsObject_QNAME, ServiceeffectiverightsObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JunctionObject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "junction_object", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "object")
    public JAXBElement<JunctionObject> createJunctionObject(JunctionObject value) {
        return new JAXBElement<JunctionObject>(_JunctionObject_QNAME, JunctionObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuditeventpolicyFilter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "auditeventpolicy_filter", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "item_filter")
    public JAXBElement<AuditeventpolicyFilter> createAuditeventpolicyFilter(AuditeventpolicyFilter value) {
        return new JAXBElement<AuditeventpolicyFilter>(_AuditeventpolicyFilter_QNAME, AuditeventpolicyFilter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegkeyauditedpermissionsObject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "regkeyauditedpermissions_object", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "object")
    public JAXBElement<RegkeyauditedpermissionsObject> createRegkeyauditedpermissionsObject(RegkeyauditedpermissionsObject value) {
        return new JAXBElement<RegkeyauditedpermissionsObject>(_RegkeyauditedpermissionsObject_QNAME, RegkeyauditedpermissionsObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Wmi57Filter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "wmi57_filter", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "item_filter")
    public JAXBElement<Wmi57Filter> createWmi57Filter(Wmi57Filter value) {
        return new JAXBElement<Wmi57Filter>(_Wmi57Filter_QNAME, Wmi57Filter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GroupFilter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "group_filter", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "item_filter")
    public JAXBElement<GroupFilter> createGroupFilter(GroupFilter value) {
        return new JAXBElement<GroupFilter>(_GroupFilter_QNAME, GroupFilter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrintereffectiverightsObject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "printereffectiverights_object", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "object")
    public JAXBElement<PrintereffectiverightsObject> createPrintereffectiverightsObject(PrintereffectiverightsObject value) {
        return new JAXBElement<PrintereffectiverightsObject>(_PrintereffectiverightsObject_QNAME, PrintereffectiverightsObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActivedirectoryFilter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "activedirectory_filter", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "item_filter")
    public JAXBElement<ActivedirectoryFilter> createActivedirectoryFilter(ActivedirectoryFilter value) {
        return new JAXBElement<ActivedirectoryFilter>(_ActivedirectoryFilter_QNAME, ActivedirectoryFilter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SharedresourceFilter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "sharedresource_filter", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "item_filter")
    public JAXBElement<SharedresourceFilter> createSharedresourceFilter(SharedresourceFilter value) {
        return new JAXBElement<SharedresourceFilter>(_SharedresourceFilter_QNAME, SharedresourceFilter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SharedresourceauditedpermissionsObject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "sharedresourceauditedpermissions_object", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "object")
    public JAXBElement<SharedresourceauditedpermissionsObject> createSharedresourceauditedpermissionsObject(SharedresourceauditedpermissionsObject value) {
        return new JAXBElement<SharedresourceauditedpermissionsObject>(_SharedresourceauditedpermissionsObject_QNAME, SharedresourceauditedpermissionsObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VolumeFilter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "volume_filter", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "item_filter")
    public JAXBElement<VolumeFilter> createVolumeFilter(VolumeFilter value) {
        return new JAXBElement<VolumeFilter>(_VolumeFilter_QNAME, VolumeFilter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FileeffectiverightsObject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "fileeffectiverights_object", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "object")
    public JAXBElement<FileeffectiverightsObject> createFileeffectiverightsObject(FileeffectiverightsObject value) {
        return new JAXBElement<FileeffectiverightsObject>(_FileeffectiverightsObject_QNAME, FileeffectiverightsObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WuaupdatesearcherObject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "wuaupdatesearcher_object", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "object")
    public JAXBElement<WuaupdatesearcherObject> createWuaupdatesearcherObject(WuaupdatesearcherObject value) {
        return new JAXBElement<WuaupdatesearcherObject>(_WuaupdatesearcherObject_QNAME, WuaupdatesearcherObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FileauditedpermissionsObject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "fileauditedpermissions_object", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "object")
    public JAXBElement<FileauditedpermissionsObject> createFileauditedpermissionsObject(FileauditedpermissionsObject value) {
        return new JAXBElement<FileauditedpermissionsObject>(_FileauditedpermissionsObject_QNAME, FileauditedpermissionsObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SystemmetricObject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "systemmetric_object", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "object")
    public JAXBElement<SystemmetricObject> createSystemmetricObject(SystemmetricObject value) {
        return new JAXBElement<SystemmetricObject>(_SystemmetricObject_QNAME, SystemmetricObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GroupSidObject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "group_sid_object", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "object")
    public JAXBElement<GroupSidObject> createGroupSidObject(GroupSidObject value) {
        return new JAXBElement<GroupSidObject>(_GroupSidObject_QNAME, GroupSidObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LicenseFilter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "license_filter", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "item_filter")
    public JAXBElement<LicenseFilter> createLicenseFilter(LicenseFilter value) {
        return new JAXBElement<LicenseFilter>(_LicenseFilter_QNAME, LicenseFilter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActivedirectoryObject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "activedirectory_object", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "object")
    public JAXBElement<ActivedirectoryObject> createActivedirectoryObject(ActivedirectoryObject value) {
        return new JAXBElement<ActivedirectoryObject>(_ActivedirectoryObject_QNAME, ActivedirectoryObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LockoutpolicyObject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "lockoutpolicy_object", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "object")
    public JAXBElement<LockoutpolicyObject> createLockoutpolicyObject(LockoutpolicyObject value) {
        return new JAXBElement<LockoutpolicyObject>(_LockoutpolicyObject_QNAME, LockoutpolicyObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NtuserFilter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "ntuser_filter", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "item_filter")
    public JAXBElement<NtuserFilter> createNtuserFilter(NtuserFilter value) {
        return new JAXBElement<NtuserFilter>(_NtuserFilter_QNAME, NtuserFilter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UacFilter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "uac_filter", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "item_filter")
    public JAXBElement<UacFilter> createUacFilter(UacFilter value) {
        return new JAXBElement<UacFilter>(_UacFilter_QNAME, UacFilter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PortObject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "port_object", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "object")
    public JAXBElement<PortObject> createPortObject(PortObject value) {
        return new JAXBElement<PortObject>(_PortObject_QNAME, PortObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SharedresourceauditedpermissionsFilter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "sharedresourceauditedpermissions_filter", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "item_filter")
    public JAXBElement<SharedresourceauditedpermissionsFilter> createSharedresourceauditedpermissionsFilter(SharedresourceauditedpermissionsFilter value) {
        return new JAXBElement<SharedresourceauditedpermissionsFilter>(_SharedresourceauditedpermissionsFilter_QNAME, SharedresourceauditedpermissionsFilter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VolumeObject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "volume_object", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "object")
    public JAXBElement<VolumeObject> createVolumeObject(VolumeObject value) {
        return new JAXBElement<VolumeObject>(_VolumeObject_QNAME, VolumeObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceFilter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "service_filter", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "item_filter")
    public JAXBElement<ServiceFilter> createServiceFilter(ServiceFilter value) {
        return new JAXBElement<ServiceFilter>(_ServiceFilter_QNAME, ServiceFilter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SharedresourceeffectiverightsObject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "sharedresourceeffectiverights_object", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "object")
    public JAXBElement<SharedresourceeffectiverightsObject> createSharedresourceeffectiverightsObject(SharedresourceeffectiverightsObject value) {
        return new JAXBElement<SharedresourceeffectiverightsObject>(_SharedresourceeffectiverightsObject_QNAME, SharedresourceeffectiverightsObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProcessFilter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "process_filter", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "item_filter")
    public JAXBElement<ProcessFilter> createProcessFilter(ProcessFilter value) {
        return new JAXBElement<ProcessFilter>(_ProcessFilter_QNAME, ProcessFilter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuditeventpolicysubcategoriesObject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "auditeventpolicysubcategories_object", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "object")
    public JAXBElement<AuditeventpolicysubcategoriesObject> createAuditeventpolicysubcategoriesObject(AuditeventpolicysubcategoriesObject value) {
        return new JAXBElement<AuditeventpolicysubcategoriesObject>(_AuditeventpolicysubcategoriesObject_QNAME, AuditeventpolicysubcategoriesObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SidFilter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "sid_filter", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "item_filter")
    public JAXBElement<SidFilter> createSidFilter(SidFilter value) {
        return new JAXBElement<SidFilter>(_SidFilter_QNAME, SidFilter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CmdletFilter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "cmdlet_filter", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "item_filter")
    public JAXBElement<CmdletFilter> createCmdletFilter(CmdletFilter value) {
        return new JAXBElement<CmdletFilter>(_CmdletFilter_QNAME, CmdletFilter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FileFilter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "file_filter", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "item_filter")
    public JAXBElement<FileFilter> createFileFilter(FileFilter value) {
        return new JAXBElement<FileFilter>(_FileFilter_QNAME, FileFilter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserSid55Filter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "user_sid55_filter", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "item_filter")
    public JAXBElement<UserSid55Filter> createUserSid55Filter(UserSid55Filter value) {
        return new JAXBElement<UserSid55Filter>(_UserSid55Filter_QNAME, UserSid55Filter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DnscacheObject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "dnscache_object", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "object")
    public JAXBElement<DnscacheObject> createDnscacheObject(DnscacheObject value) {
        return new JAXBElement<DnscacheObject>(_DnscacheObject_QNAME, DnscacheObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SidSidObject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "sid_sid_object", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "object")
    public JAXBElement<SidSidObject> createSidSidObject(SidSidObject value) {
        return new JAXBElement<SidSidObject>(_SidSidObject_QNAME, SidSidObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PeheaderFilter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "peheader_filter", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "item_filter")
    public JAXBElement<PeheaderFilter> createPeheaderFilter(PeheaderFilter value) {
        return new JAXBElement<PeheaderFilter>(_PeheaderFilter_QNAME, PeheaderFilter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MetabaseFilter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "metabase_filter", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "item_filter")
    public JAXBElement<MetabaseFilter> createMetabaseFilter(MetabaseFilter value) {
        return new JAXBElement<MetabaseFilter>(_MetabaseFilter_QNAME, MetabaseFilter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserObject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "user_object", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "object")
    public JAXBElement<UserObject> createUserObject(UserObject value) {
        return new JAXBElement<UserObject>(_UserObject_QNAME, UserObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrintereffectiverightsFilter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "printereffectiverights_filter", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "item_filter")
    public JAXBElement<PrintereffectiverightsFilter> createPrintereffectiverightsFilter(PrintereffectiverightsFilter value) {
        return new JAXBElement<PrintereffectiverightsFilter>(_PrintereffectiverightsFilter_QNAME, PrintereffectiverightsFilter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SidSidFilter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "sid_sid_filter", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "item_filter")
    public JAXBElement<SidSidFilter> createSidSidFilter(SidSidFilter value) {
        return new JAXBElement<SidSidFilter>(_SidSidFilter_QNAME, SidSidFilter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserSid55Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "user_sid55_object", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "object")
    public JAXBElement<UserSid55Object> createUserSid55Object(UserSid55Object value) {
        return new JAXBElement<UserSid55Object>(_UserSid55Object_QNAME, UserSid55Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CmdletObject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "cmdlet_object", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "object")
    public JAXBElement<CmdletObject> createCmdletObject(CmdletObject value) {
        return new JAXBElement<CmdletObject>(_CmdletObject_QNAME, CmdletObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FileObject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "file_object", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "object")
    public JAXBElement<FileObject> createFileObject(FileObject value) {
        return new JAXBElement<FileObject>(_FileObject_QNAME, FileObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Wmi57Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "wmi57_object", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "object")
    public JAXBElement<Wmi57Object> createWmi57Object(Wmi57Object value) {
        return new JAXBElement<Wmi57Object>(_Wmi57Object_QNAME, Wmi57Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FileeffectiverightsFilter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "fileeffectiverights_filter", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "item_filter")
    public JAXBElement<FileeffectiverightsFilter> createFileeffectiverightsFilter(FileeffectiverightsFilter value) {
        return new JAXBElement<FileeffectiverightsFilter>(_FileeffectiverightsFilter_QNAME, FileeffectiverightsFilter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SharedresourceObject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "sharedresource_object", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "object")
    public JAXBElement<SharedresourceObject> createSharedresourceObject(SharedresourceObject value) {
        return new JAXBElement<SharedresourceObject>(_SharedresourceObject_QNAME, SharedresourceObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PeheaderObject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "peheader_object", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "object")
    public JAXBElement<PeheaderObject> createPeheaderObject(PeheaderObject value) {
        return new JAXBElement<PeheaderObject>(_PeheaderObject_QNAME, PeheaderObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InterfaceObject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "interface_object", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "object")
    public JAXBElement<InterfaceObject> createInterfaceObject(InterfaceObject value) {
        return new JAXBElement<InterfaceObject>(_InterfaceObject_QNAME, InterfaceObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InterfaceFilter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "interface_filter", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "item_filter")
    public JAXBElement<InterfaceFilter> createInterfaceFilter(InterfaceFilter value) {
        return new JAXBElement<InterfaceFilter>(_InterfaceFilter_QNAME, InterfaceFilter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceeffectiverightsFilter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "serviceeffectiverights_filter", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "item_filter")
    public JAXBElement<ServiceeffectiverightsFilter> createServiceeffectiverightsFilter(ServiceeffectiverightsFilter value) {
        return new JAXBElement<ServiceeffectiverightsFilter>(_ServiceeffectiverightsFilter_QNAME, ServiceeffectiverightsFilter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JunctionFilter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "junction_filter", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "item_filter")
    public JAXBElement<JunctionFilter> createJunctionFilter(JunctionFilter value) {
        return new JAXBElement<JunctionFilter>(_JunctionFilter_QNAME, JunctionFilter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserrightFilter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "userright_filter", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "item_filter")
    public JAXBElement<UserrightFilter> createUserrightFilter(UserrightFilter value) {
        return new JAXBElement<UserrightFilter>(_UserrightFilter_QNAME, UserrightFilter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegkeyauditedpermissionsFilter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "regkeyauditedpermissions_filter", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "item_filter")
    public JAXBElement<RegkeyauditedpermissionsFilter> createRegkeyauditedpermissionsFilter(RegkeyauditedpermissionsFilter value) {
        return new JAXBElement<RegkeyauditedpermissionsFilter>(_RegkeyauditedpermissionsFilter_QNAME, RegkeyauditedpermissionsFilter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuditeventpolicyObject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "auditeventpolicy_object", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "object")
    public JAXBElement<AuditeventpolicyObject> createAuditeventpolicyObject(AuditeventpolicyObject value) {
        return new JAXBElement<AuditeventpolicyObject>(_AuditeventpolicyObject_QNAME, AuditeventpolicyObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GroupObject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "group_object", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "object")
    public JAXBElement<GroupObject> createGroupObject(GroupObject value) {
        return new JAXBElement<GroupObject>(_GroupObject_QNAME, GroupObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegistryFilter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "registry_filter", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "item_filter")
    public JAXBElement<RegistryFilter> createRegistryFilter(RegistryFilter value) {
        return new JAXBElement<RegistryFilter>(_RegistryFilter_QNAME, RegistryFilter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PasswordpolicyObject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "passwordpolicy_object", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "object")
    public JAXBElement<PasswordpolicyObject> createPasswordpolicyObject(PasswordpolicyObject value) {
        return new JAXBElement<PasswordpolicyObject>(_PasswordpolicyObject_QNAME, PasswordpolicyObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PortFilter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "port_filter", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "item_filter")
    public JAXBElement<PortFilter> createPortFilter(PortFilter value) {
        return new JAXBElement<PortFilter>(_PortFilter_QNAME, PortFilter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegkeyeffectiverightsFilter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "regkeyeffectiverights_filter", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "item_filter")
    public JAXBElement<RegkeyeffectiverightsFilter> createRegkeyeffectiverightsFilter(RegkeyeffectiverightsFilter value) {
        return new JAXBElement<RegkeyeffectiverightsFilter>(_RegkeyeffectiverightsFilter_QNAME, RegkeyeffectiverightsFilter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FileauditedpermissionsFilter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "fileauditedpermissions_filter", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "item_filter")
    public JAXBElement<FileauditedpermissionsFilter> createFileauditedpermissionsFilter(FileauditedpermissionsFilter value) {
        return new JAXBElement<FileauditedpermissionsFilter>(_FileauditedpermissionsFilter_QNAME, FileauditedpermissionsFilter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LicenseObject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "license_object", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "object")
    public JAXBElement<LicenseObject> createLicenseObject(LicenseObject value) {
        return new JAXBElement<LicenseObject>(_LicenseObject_QNAME, LicenseObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserFilter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "user_filter", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "item_filter")
    public JAXBElement<UserFilter> createUserFilter(UserFilter value) {
        return new JAXBElement<UserFilter>(_UserFilter_QNAME, UserFilter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WuaupdatesearcherFilter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "wuaupdatesearcher_filter", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "item_filter")
    public JAXBElement<WuaupdatesearcherFilter> createWuaupdatesearcherFilter(WuaupdatesearcherFilter value) {
        return new JAXBElement<WuaupdatesearcherFilter>(_WuaupdatesearcherFilter_QNAME, WuaupdatesearcherFilter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NtuserObject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "ntuser_object", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "object")
    public JAXBElement<NtuserObject> createNtuserObject(NtuserObject value) {
        return new JAXBElement<NtuserObject>(_NtuserObject_QNAME, NtuserObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LockoutpolicyFilter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "lockoutpolicy_filter", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "item_filter")
    public JAXBElement<LockoutpolicyFilter> createLockoutpolicyFilter(LockoutpolicyFilter value) {
        return new JAXBElement<LockoutpolicyFilter>(_LockoutpolicyFilter_QNAME, LockoutpolicyFilter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SidObject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "sid_object", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "object")
    public JAXBElement<SidObject> createSidObject(SidObject value) {
        return new JAXBElement<SidObject>(_SidObject_QNAME, SidObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UacObject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "uac_object", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "object")
    public JAXBElement<UacObject> createUacObject(UacObject value) {
        return new JAXBElement<UacObject>(_UacObject_QNAME, UacObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProcessObject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "process_object", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "object")
    public JAXBElement<ProcessObject> createProcessObject(ProcessObject value) {
        return new JAXBElement<ProcessObject>(_ProcessObject_QNAME, ProcessObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegistryObject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "registry_object", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "object")
    public JAXBElement<RegistryObject> createRegistryObject(RegistryObject value) {
        return new JAXBElement<RegistryObject>(_RegistryObject_QNAME, RegistryObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SystemmetricFilter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "systemmetric_filter", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "item_filter")
    public JAXBElement<SystemmetricFilter> createSystemmetricFilter(SystemmetricFilter value) {
        return new JAXBElement<SystemmetricFilter>(_SystemmetricFilter_QNAME, SystemmetricFilter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuditeventpolicysubcategoriesFilter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "auditeventpolicysubcategories_filter", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "item_filter")
    public JAXBElement<AuditeventpolicysubcategoriesFilter> createAuditeventpolicysubcategoriesFilter(AuditeventpolicysubcategoriesFilter value) {
        return new JAXBElement<AuditeventpolicysubcategoriesFilter>(_AuditeventpolicysubcategoriesFilter_QNAME, AuditeventpolicysubcategoriesFilter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceObject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "service_object", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "object")
    public JAXBElement<ServiceObject> createServiceObject(ServiceObject value) {
        return new JAXBElement<ServiceObject>(_ServiceObject_QNAME, ServiceObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SharedresourceeffectiverightsFilter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "sharedresourceeffectiverights_filter", substitutionHeadNamespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", substitutionHeadName = "item_filter")
    public JAXBElement<SharedresourceeffectiverightsFilter> createSharedresourceeffectiverightsFilter(SharedresourceeffectiverightsFilter value) {
        return new JAXBElement<SharedresourceeffectiverightsFilter>(_SharedresourceeffectiverightsFilter_QNAME, SharedresourceeffectiverightsFilter.class, null, value);
    }

//    /**
//     * Create an instance of {@link JAXBElement }{@code <}{@link FilterType }{@code >}}
//     *
//     */
//    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6", name = "item_filter")
//    public JAXBElement<FilterType> createItemFilter(FilterType value) {
//        return new JAXBElement<FilterType>(_ItemFilter_QNAME, FilterType.class, null, value);
//    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectStringType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "filename", scope = FileeffectiverightsObject.class)
    public JAXBElement<ObjectStringType> createFileeffectiverightsObjectFilename(ObjectStringType value) {
        return new JAXBElement<ObjectStringType>(_FileeffectiverightsObjectFilename_QNAME, ObjectStringType.class, FileeffectiverightsObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectStringType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "key", scope = RegkeyeffectiverightsObject.class)
    public JAXBElement<ObjectStringType> createRegkeyeffectiverightsObjectKey(ObjectStringType value) {
        return new JAXBElement<ObjectStringType>(_RegkeyeffectiverightsObjectKey_QNAME, ObjectStringType.class, RegkeyeffectiverightsObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectIntType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "id", scope = MetabaseObject.class)
    public JAXBElement<ObjectIntType> createMetabaseObjectId(ObjectIntType value) {
        return new JAXBElement<ObjectIntType>(_MetabaseObjectId_QNAME, ObjectIntType.class, MetabaseObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectStringType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "filename", scope = FileauditedpermissionsObject.class)
    public JAXBElement<ObjectStringType> createFileauditedpermissionsObjectFilename(ObjectStringType value) {
        return new JAXBElement<ObjectStringType>(_FileeffectiverightsObjectFilename_QNAME, ObjectStringType.class, FileauditedpermissionsObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectStringType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "name", scope = NtuserObject.class)
    public JAXBElement<ObjectStringType> createNtuserObjectName(ObjectStringType value) {
        return new JAXBElement<ObjectStringType>(_NtuserObjectName_QNAME, ObjectStringType.class, NtuserObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectStringType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "attribute", scope = ActivedirectoryObject.class)
    public JAXBElement<ObjectStringType> createActivedirectoryObjectAttribute(ObjectStringType value) {
        return new JAXBElement<ObjectStringType>(_ActivedirectoryObjectAttribute_QNAME, ObjectStringType.class, ActivedirectoryObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectStringType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "relative_dn", scope = ActivedirectoryObject.class)
    public JAXBElement<ObjectStringType> createActivedirectoryObjectRelativeDn(ObjectStringType value) {
        return new JAXBElement<ObjectStringType>(_ActivedirectoryObjectRelativeDn_QNAME, ObjectStringType.class, ActivedirectoryObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectStringType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "filename", scope = FileObject.class)
    public JAXBElement<ObjectStringType> createFileObjectFilename(ObjectStringType value) {
        return new JAXBElement<ObjectStringType>(_FileeffectiverightsObjectFilename_QNAME, ObjectStringType.class, FileObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectStringType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "command_line", scope = ProcessObject.class)
    public JAXBElement<ObjectStringType> createProcessObjectCommandLine(ObjectStringType value) {
        return new JAXBElement<ObjectStringType>(_ProcessObjectCommandLine_QNAME, ObjectStringType.class, ProcessObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectStringType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "key", scope = RegkeyauditedpermissionsObject.class)
    public JAXBElement<ObjectStringType> createRegkeyauditedpermissionsObjectKey(ObjectStringType value) {
        return new JAXBElement<ObjectStringType>(_RegkeyeffectiverightsObjectKey_QNAME, ObjectStringType.class, RegkeyauditedpermissionsObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectStringType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "key", scope = RegistryObject.class)
    public JAXBElement<ObjectStringType> createRegistryObjectKey(ObjectStringType value) {
        return new JAXBElement<ObjectStringType>(_RegkeyeffectiverightsObjectKey_QNAME, ObjectStringType.class, RegistryObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectStringType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "name", scope = RegistryObject.class)
    public JAXBElement<ObjectStringType> createRegistryObjectName(ObjectStringType value) {
        return new JAXBElement<ObjectStringType>(_NtuserObjectName_QNAME, ObjectStringType.class, RegistryObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectRecordType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "parameters", scope = CmdletObject.class)
    public JAXBElement<ObjectRecordType> createCmdletObjectParameters(ObjectRecordType value) {
        return new JAXBElement<ObjectRecordType>(_CmdletObjectParameters_QNAME, ObjectRecordType.class, CmdletObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectVersionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "module_version", scope = CmdletObject.class)
    public JAXBElement<ObjectVersionType> createCmdletObjectModuleVersion(ObjectVersionType value) {
        return new JAXBElement<ObjectVersionType>(_CmdletObjectModuleVersion_QNAME, ObjectVersionType.class, CmdletObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectStringType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "module_name", scope = CmdletObject.class)
    public JAXBElement<ObjectStringType> createCmdletObjectModuleName(ObjectStringType value) {
        return new JAXBElement<ObjectStringType>(_CmdletObjectModuleName_QNAME, ObjectStringType.class, CmdletObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectGUIDType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "module_id", scope = CmdletObject.class)
    public JAXBElement<ObjectGUIDType> createCmdletObjectModuleId(ObjectGUIDType value) {
        return new JAXBElement<ObjectGUIDType>(_CmdletObjectModuleId_QNAME, ObjectGUIDType.class, CmdletObject.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectRecordType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows", name = "select", scope = CmdletObject.class)
    public JAXBElement<ObjectRecordType> createCmdletObjectSelect(ObjectRecordType value) {
        return new JAXBElement<ObjectRecordType>(_CmdletObjectSelect_QNAME, ObjectRecordType.class, CmdletObject.class, value);
    }

}
