//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.21 at 11:38:45 AM EST 
//

@javax.xml.bind.annotation.XmlSchema(
	namespace = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows",
	elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
	xmlns = {
		@XmlNs(prefix="win-coll", namespaceURI = "http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows")
	}
)
package org.cisecurity.oval.collection.win;

import javax.xml.bind.annotation.XmlNs;
