//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.21 at 11:38:45 AM EST 
//


package org.cisecurity.oval.collection.win;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.cisecurity.oval.collection.FilterAnySimpleType;
import org.cisecurity.oval.collection.FilterIntType;
import org.cisecurity.oval.collection.FilterStringType;
import org.cisecurity.oval.collection.FilterType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://oval.cisecurity.org/XMLSchema/oval-collections-6}FilterType">
 *       &lt;sequence>
 *         &lt;element name="hive" type="{http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows}FilterRegistryHiveType" minOccurs="0"/>
 *         &lt;element name="key" type="{http://oval.cisecurity.org/XMLSchema/oval-collections-6}FilterStringType" minOccurs="0"/>
 *         &lt;element name="name" type="{http://oval.cisecurity.org/XMLSchema/oval-collections-6}FilterStringType" minOccurs="0"/>
 *         &lt;element name="last_write_time" type="{http://oval.cisecurity.org/XMLSchema/oval-collections-6}FilterIntType" minOccurs="0"/>
 *         &lt;element name="type" type="{http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows}FilterRegistryTypeType" minOccurs="0"/>
 *         &lt;element name="value" type="{http://oval.cisecurity.org/XMLSchema/oval-collections-6}FilterAnySimpleType" minOccurs="0"/>
 *         &lt;element name="expanded_value" type="{http://oval.cisecurity.org/XMLSchema/oval-collections-6}FilterAnySimpleType" minOccurs="0"/>
 *         &lt;element name="windows_view" type="{http://oval.cisecurity.org/XMLSchema/oval-collections-6#windows}FilterWindowsViewType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "hive",
    "key",
    "name",
    "lastWriteTime",
    "type",
    "value",
    "expandedValue",
    "windowsView"
})
public class RegistryFilter
    extends FilterType
{

    protected FilterRegistryHiveType hive;
    protected FilterStringType key;
    protected FilterStringType name;
    @XmlElement(name = "last_write_time")
    protected FilterIntType lastWriteTime;
    protected FilterRegistryTypeType type;
    protected FilterAnySimpleType value;
    @XmlElement(name = "expanded_value")
    protected FilterAnySimpleType expandedValue;
    @XmlElement(name = "windows_view")
    protected FilterWindowsViewType windowsView;

    /**
     * Gets the value of the hive property.
     * 
     * @return
     *     possible object is
     *     {@link FilterRegistryHiveType }
     *     
     */
    public FilterRegistryHiveType getHive() {
        return hive;
    }

    /**
     * Sets the value of the hive property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterRegistryHiveType }
     *     
     */
    public void setHive(FilterRegistryHiveType value) {
        this.hive = value;
    }

    /**
     * Gets the value of the key property.
     * 
     * @return
     *     possible object is
     *     {@link FilterStringType }
     *     
     */
    public FilterStringType getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterStringType }
     *     
     */
    public void setKey(FilterStringType value) {
        this.key = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link FilterStringType }
     *     
     */
    public FilterStringType getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterStringType }
     *     
     */
    public void setName(FilterStringType value) {
        this.name = value;
    }

    /**
     * Gets the value of the lastWriteTime property.
     * 
     * @return
     *     possible object is
     *     {@link FilterIntType }
     *     
     */
    public FilterIntType getLastWriteTime() {
        return lastWriteTime;
    }

    /**
     * Sets the value of the lastWriteTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterIntType }
     *     
     */
    public void setLastWriteTime(FilterIntType value) {
        this.lastWriteTime = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link FilterRegistryTypeType }
     *     
     */
    public FilterRegistryTypeType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterRegistryTypeType }
     *     
     */
    public void setType(FilterRegistryTypeType value) {
        this.type = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link FilterAnySimpleType }
     *     
     */
    public FilterAnySimpleType getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterAnySimpleType }
     *     
     */
    public void setValue(FilterAnySimpleType value) {
        this.value = value;
    }

    /**
     * Gets the value of the expandedValue property.
     * 
     * @return
     *     possible object is
     *     {@link FilterAnySimpleType }
     *     
     */
    public FilterAnySimpleType getExpandedValue() {
        return expandedValue;
    }

    /**
     * Sets the value of the expandedValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterAnySimpleType }
     *     
     */
    public void setExpandedValue(FilterAnySimpleType value) {
        this.expandedValue = value;
    }

    /**
     * Gets the value of the windowsView property.
     * 
     * @return
     *     possible object is
     *     {@link FilterWindowsViewType }
     *     
     */
    public FilterWindowsViewType getWindowsView() {
        return windowsView;
    }

    /**
     * Sets the value of the windowsView property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterWindowsViewType }
     *     
     */
    public void setWindowsView(FilterWindowsViewType value) {
        this.windowsView = value;
    }

}
