//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.21 at 11:38:45 AM EST 
//


package org.cisecurity.oval.collection.win;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.cisecurity.oval.collection.FilterBoolType;
import org.cisecurity.oval.collection.FilterStringType;
import org.cisecurity.oval.collection.FilterType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://oval.cisecurity.org/XMLSchema/oval-collections-6}FilterType">
 *       &lt;sequence>
 *         &lt;element name="service_name" type="{http://oval.cisecurity.org/XMLSchema/oval-collections-6}FilterStringType" minOccurs="0"/>
 *         &lt;element name="trustee_sid" type="{http://oval.cisecurity.org/XMLSchema/oval-collections-6}FilterStringType" minOccurs="0"/>
 *         &lt;element name="standard_delete" type="{http://oval.cisecurity.org/XMLSchema/oval-collections-6}FilterBoolType" minOccurs="0"/>
 *         &lt;element name="standard_read_control" type="{http://oval.cisecurity.org/XMLSchema/oval-collections-6}FilterBoolType" minOccurs="0"/>
 *         &lt;element name="standard_write_dac" type="{http://oval.cisecurity.org/XMLSchema/oval-collections-6}FilterBoolType" minOccurs="0"/>
 *         &lt;element name="standard_write_owner" type="{http://oval.cisecurity.org/XMLSchema/oval-collections-6}FilterBoolType" minOccurs="0"/>
 *         &lt;element name="generic_read" type="{http://oval.cisecurity.org/XMLSchema/oval-collections-6}FilterBoolType" minOccurs="0"/>
 *         &lt;element name="generic_write" type="{http://oval.cisecurity.org/XMLSchema/oval-collections-6}FilterBoolType" minOccurs="0"/>
 *         &lt;element name="generic_execute" type="{http://oval.cisecurity.org/XMLSchema/oval-collections-6}FilterBoolType" minOccurs="0"/>
 *         &lt;element name="service_query_conf" type="{http://oval.cisecurity.org/XMLSchema/oval-collections-6}FilterBoolType" minOccurs="0"/>
 *         &lt;element name="service_change_conf" type="{http://oval.cisecurity.org/XMLSchema/oval-collections-6}FilterBoolType" minOccurs="0"/>
 *         &lt;element name="service_query_stat" type="{http://oval.cisecurity.org/XMLSchema/oval-collections-6}FilterBoolType" minOccurs="0"/>
 *         &lt;element name="service_enum_dependents" type="{http://oval.cisecurity.org/XMLSchema/oval-collections-6}FilterBoolType" minOccurs="0"/>
 *         &lt;element name="service_start" type="{http://oval.cisecurity.org/XMLSchema/oval-collections-6}FilterBoolType" minOccurs="0"/>
 *         &lt;element name="service_stop" type="{http://oval.cisecurity.org/XMLSchema/oval-collections-6}FilterBoolType" minOccurs="0"/>
 *         &lt;element name="service_pause" type="{http://oval.cisecurity.org/XMLSchema/oval-collections-6}FilterBoolType" minOccurs="0"/>
 *         &lt;element name="service_interrogate" type="{http://oval.cisecurity.org/XMLSchema/oval-collections-6}FilterBoolType" minOccurs="0"/>
 *         &lt;element name="service_user_defined" type="{http://oval.cisecurity.org/XMLSchema/oval-collections-6}FilterBoolType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "serviceName",
    "trusteeSid",
    "standardDelete",
    "standardReadControl",
    "standardWriteDac",
    "standardWriteOwner",
    "genericRead",
    "genericWrite",
    "genericExecute",
    "serviceQueryConf",
    "serviceChangeConf",
    "serviceQueryStat",
    "serviceEnumDependents",
    "serviceStart",
    "serviceStop",
    "servicePause",
    "serviceInterrogate",
    "serviceUserDefined"
})
public class ServiceeffectiverightsFilter
    extends FilterType
{

    @XmlElement(name = "service_name")
    protected FilterStringType serviceName;
    @XmlElement(name = "trustee_sid")
    protected FilterStringType trusteeSid;
    @XmlElement(name = "standard_delete")
    protected FilterBoolType standardDelete;
    @XmlElement(name = "standard_read_control")
    protected FilterBoolType standardReadControl;
    @XmlElement(name = "standard_write_dac")
    protected FilterBoolType standardWriteDac;
    @XmlElement(name = "standard_write_owner")
    protected FilterBoolType standardWriteOwner;
    @XmlElement(name = "generic_read")
    protected FilterBoolType genericRead;
    @XmlElement(name = "generic_write")
    protected FilterBoolType genericWrite;
    @XmlElement(name = "generic_execute")
    protected FilterBoolType genericExecute;
    @XmlElement(name = "service_query_conf")
    protected FilterBoolType serviceQueryConf;
    @XmlElement(name = "service_change_conf")
    protected FilterBoolType serviceChangeConf;
    @XmlElement(name = "service_query_stat")
    protected FilterBoolType serviceQueryStat;
    @XmlElement(name = "service_enum_dependents")
    protected FilterBoolType serviceEnumDependents;
    @XmlElement(name = "service_start")
    protected FilterBoolType serviceStart;
    @XmlElement(name = "service_stop")
    protected FilterBoolType serviceStop;
    @XmlElement(name = "service_pause")
    protected FilterBoolType servicePause;
    @XmlElement(name = "service_interrogate")
    protected FilterBoolType serviceInterrogate;
    @XmlElement(name = "service_user_defined")
    protected FilterBoolType serviceUserDefined;

    /**
     * Gets the value of the serviceName property.
     * 
     * @return
     *     possible object is
     *     {@link FilterStringType }
     *     
     */
    public FilterStringType getServiceName() {
        return serviceName;
    }

    /**
     * Sets the value of the serviceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterStringType }
     *     
     */
    public void setServiceName(FilterStringType value) {
        this.serviceName = value;
    }

    /**
     * Gets the value of the trusteeSid property.
     * 
     * @return
     *     possible object is
     *     {@link FilterStringType }
     *     
     */
    public FilterStringType getTrusteeSid() {
        return trusteeSid;
    }

    /**
     * Sets the value of the trusteeSid property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterStringType }
     *     
     */
    public void setTrusteeSid(FilterStringType value) {
        this.trusteeSid = value;
    }

    /**
     * Gets the value of the standardDelete property.
     * 
     * @return
     *     possible object is
     *     {@link FilterBoolType }
     *     
     */
    public FilterBoolType getStandardDelete() {
        return standardDelete;
    }

    /**
     * Sets the value of the standardDelete property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterBoolType }
     *     
     */
    public void setStandardDelete(FilterBoolType value) {
        this.standardDelete = value;
    }

    /**
     * Gets the value of the standardReadControl property.
     * 
     * @return
     *     possible object is
     *     {@link FilterBoolType }
     *     
     */
    public FilterBoolType getStandardReadControl() {
        return standardReadControl;
    }

    /**
     * Sets the value of the standardReadControl property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterBoolType }
     *     
     */
    public void setStandardReadControl(FilterBoolType value) {
        this.standardReadControl = value;
    }

    /**
     * Gets the value of the standardWriteDac property.
     * 
     * @return
     *     possible object is
     *     {@link FilterBoolType }
     *     
     */
    public FilterBoolType getStandardWriteDac() {
        return standardWriteDac;
    }

    /**
     * Sets the value of the standardWriteDac property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterBoolType }
     *     
     */
    public void setStandardWriteDac(FilterBoolType value) {
        this.standardWriteDac = value;
    }

    /**
     * Gets the value of the standardWriteOwner property.
     * 
     * @return
     *     possible object is
     *     {@link FilterBoolType }
     *     
     */
    public FilterBoolType getStandardWriteOwner() {
        return standardWriteOwner;
    }

    /**
     * Sets the value of the standardWriteOwner property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterBoolType }
     *     
     */
    public void setStandardWriteOwner(FilterBoolType value) {
        this.standardWriteOwner = value;
    }

    /**
     * Gets the value of the genericRead property.
     * 
     * @return
     *     possible object is
     *     {@link FilterBoolType }
     *     
     */
    public FilterBoolType getGenericRead() {
        return genericRead;
    }

    /**
     * Sets the value of the genericRead property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterBoolType }
     *     
     */
    public void setGenericRead(FilterBoolType value) {
        this.genericRead = value;
    }

    /**
     * Gets the value of the genericWrite property.
     * 
     * @return
     *     possible object is
     *     {@link FilterBoolType }
     *     
     */
    public FilterBoolType getGenericWrite() {
        return genericWrite;
    }

    /**
     * Sets the value of the genericWrite property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterBoolType }
     *     
     */
    public void setGenericWrite(FilterBoolType value) {
        this.genericWrite = value;
    }

    /**
     * Gets the value of the genericExecute property.
     * 
     * @return
     *     possible object is
     *     {@link FilterBoolType }
     *     
     */
    public FilterBoolType getGenericExecute() {
        return genericExecute;
    }

    /**
     * Sets the value of the genericExecute property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterBoolType }
     *     
     */
    public void setGenericExecute(FilterBoolType value) {
        this.genericExecute = value;
    }

    /**
     * Gets the value of the serviceQueryConf property.
     * 
     * @return
     *     possible object is
     *     {@link FilterBoolType }
     *     
     */
    public FilterBoolType getServiceQueryConf() {
        return serviceQueryConf;
    }

    /**
     * Sets the value of the serviceQueryConf property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterBoolType }
     *     
     */
    public void setServiceQueryConf(FilterBoolType value) {
        this.serviceQueryConf = value;
    }

    /**
     * Gets the value of the serviceChangeConf property.
     * 
     * @return
     *     possible object is
     *     {@link FilterBoolType }
     *     
     */
    public FilterBoolType getServiceChangeConf() {
        return serviceChangeConf;
    }

    /**
     * Sets the value of the serviceChangeConf property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterBoolType }
     *     
     */
    public void setServiceChangeConf(FilterBoolType value) {
        this.serviceChangeConf = value;
    }

    /**
     * Gets the value of the serviceQueryStat property.
     * 
     * @return
     *     possible object is
     *     {@link FilterBoolType }
     *     
     */
    public FilterBoolType getServiceQueryStat() {
        return serviceQueryStat;
    }

    /**
     * Sets the value of the serviceQueryStat property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterBoolType }
     *     
     */
    public void setServiceQueryStat(FilterBoolType value) {
        this.serviceQueryStat = value;
    }

    /**
     * Gets the value of the serviceEnumDependents property.
     * 
     * @return
     *     possible object is
     *     {@link FilterBoolType }
     *     
     */
    public FilterBoolType getServiceEnumDependents() {
        return serviceEnumDependents;
    }

    /**
     * Sets the value of the serviceEnumDependents property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterBoolType }
     *     
     */
    public void setServiceEnumDependents(FilterBoolType value) {
        this.serviceEnumDependents = value;
    }

    /**
     * Gets the value of the serviceStart property.
     * 
     * @return
     *     possible object is
     *     {@link FilterBoolType }
     *     
     */
    public FilterBoolType getServiceStart() {
        return serviceStart;
    }

    /**
     * Sets the value of the serviceStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterBoolType }
     *     
     */
    public void setServiceStart(FilterBoolType value) {
        this.serviceStart = value;
    }

    /**
     * Gets the value of the serviceStop property.
     * 
     * @return
     *     possible object is
     *     {@link FilterBoolType }
     *     
     */
    public FilterBoolType getServiceStop() {
        return serviceStop;
    }

    /**
     * Sets the value of the serviceStop property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterBoolType }
     *     
     */
    public void setServiceStop(FilterBoolType value) {
        this.serviceStop = value;
    }

    /**
     * Gets the value of the servicePause property.
     * 
     * @return
     *     possible object is
     *     {@link FilterBoolType }
     *     
     */
    public FilterBoolType getServicePause() {
        return servicePause;
    }

    /**
     * Sets the value of the servicePause property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterBoolType }
     *     
     */
    public void setServicePause(FilterBoolType value) {
        this.servicePause = value;
    }

    /**
     * Gets the value of the serviceInterrogate property.
     * 
     * @return
     *     possible object is
     *     {@link FilterBoolType }
     *     
     */
    public FilterBoolType getServiceInterrogate() {
        return serviceInterrogate;
    }

    /**
     * Sets the value of the serviceInterrogate property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterBoolType }
     *     
     */
    public void setServiceInterrogate(FilterBoolType value) {
        this.serviceInterrogate = value;
    }

    /**
     * Gets the value of the serviceUserDefined property.
     * 
     * @return
     *     possible object is
     *     {@link FilterBoolType }
     *     
     */
    public FilterBoolType getServiceUserDefined() {
        return serviceUserDefined;
    }

    /**
     * Sets the value of the serviceUserDefined property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterBoolType }
     *     
     */
    public void setServiceUserDefined(FilterBoolType value) {
        this.serviceUserDefined = value;
    }

}
